### ISSUE TITLE
add explicit encoding='utf8' to setup.py?

### ISSUE THREAD

**Issue by mjgreen** [MatthewBCooke/Pathfinder#1]
Can I suggest the following in setup.py?
(add encoding = utf8)
python setup install failed until I added this, using windows7 and anaconda3 and Pathfinder cloned from repo
pip install jsl-pathfinder failed too, with file encoding complaints

```
with open('README.txt', encoding="utf8") as file:
    long_description = file.read()
```

**Comment by mjgreen** [comment]
sorry, I should have typed README.md not .txt:

`with open('README.md', encoding="utf8") as f:
    long_description = f.read()
`

**Comment by MatthewBCooke** [comment]
Sorry about that, minimal testing has been done on the Windows end. Resolved.
