### ISSUE TITLE
unable to launch the GUI

### ISSUE THREAD

**Issue by Gfernandezv** [MatthewBCooke/Pathfinder#12]
I just cloned the repository but failed launched the GUI in anaconda

**Comment by mapkinase** [comment]
I had a lot of problems to get the GUI running. I'm by no means an expert, but I managed to get the GUI after cloning the repository with git bash. Then, in the directory created (SearchStrategyAnalysis) I just clicked the Pathfinder file and it opened the GUI. Hope it helps

**Comment by Gfernandezv** [comment]
nop, don't work for me =(.

thanks

**Comment by MatthewBCooke** [comment]
try using pypi: in a terminal window, type `pip install jsl-pathfinder`
then, once installed type `pathfinder` to launch
