### ISSUE TITLE
 CSV file does not appear

### ISSUE THREAD

**Issue by kstefanoska** [MatthewBCooke/Pathfinder#16]
Hi once I calculate the search strategy the CSV file does not appear?

**Comment by MatthewBCooke** [comment]
So the output file should appear in a folder called output in the directory where pathfinder is located. If you can verify that the output folder exists that would be step one. If not, is the program creating logs (should be in the same place but a folder called logs)?

**Comment by kstefanoska** [comment]
yes you are right found them thank you
