### ISSUE TITLE
Ethovision doesn't finish calculating strategy

### ISSUE THREAD

**Issue by IADoronin** [MatthewBCooke/Pathfinder#3]
A problem with software occured.
I tried an example file Ethovision.xlsx.  from https://drive.google.com/drive/folders/1K285EjiSynD4VteqV1O1PkNwTUODW9PK
I started pathfinder, opened file Ethovision.xlsx, filled parameters and then push calculate.
It starts calculating, creating file results 2019_11_27 03_43_23_PM-36,42.csv in folder **results**, but this file has just one strategy. I receive the same result when open folder with my files. 

![Calculating](https://user-images.githubusercontent.com/32221283/69724977-2d09b480-112e-11ea-8ba8-af7a5a116b44.png)

![Снимок экрана (78)](https://user-images.githubusercontent.com/32221283/69725626-9d650580-112f-11ea-8ec7-8374dc286e16.png)

**Comment by MatthewBCooke** [comment]
Sorry for the late reply, the provided Ethovision file is a single trial. This is the expected output.
