### ISSUE TITLE
Unable to run tutorial!

### ISSUE THREAD

**Issue by james-vizag** [MatthewBCooke/Pathfinder#4]
Hi, I am trying to run the tutorial of Pathfinder. I downloaded the files from G-drive. At 3rd step, when I chose WaterMaze as sample dataset and run the analysis with parameters at Auto, it goes into "Calculating search strategies" for indefinite time. Also, when I click settings tab, it is unable to scroll down, thus couldn't see the lower parameters.
Do you have a video or an elaborate tutorial to follow the process in an easy way.
![pathfinder-settings](https://user-images.githubusercontent.com/65596783/82314164-02b2f880-99e7-11ea-8e45-32cdb217627d.png)

**Comment by bdungate** [comment]
In the current release on PyPi there is no scroll bar, but we've fixed this on the version that is currently available on GitHub. You can follow the instructions on the installation page on how to clone the files to your machine, that should fix the scrollbar issue for now. The functionality will be updated in the next release on PyPi. For the unending "calculating strategies" issue, are you selecting "Watermaze" as the option on the top row of the window (on the same line as "Define")? If not, that may be what's causing the issue. If you have selected Watermaze I can look into the issue further, as of right now I can't seem to replicate that issue on my machine.

**Comment by MatthewBCooke** [comment]
@james-vizag has updating the software solved your issue? I will close the issue if this is solved -
Matthew

**Comment by james-vizag** [comment]
Thank you Matthew. Apologies for the delay. Yes, we can close the issue. I will explore this issue more in details soon.
