### ISSUE TITLE
Barnes application question

### ISSUE THREAD

**Issue by filos93** [MatthewBCooke/Pathfinder#9]
Hey sorry to bother you, thanks for the great software seems very user-friendly and efficient, I was wondering if you have suggestions-recommendations for applying your software to Barnes experimental setting/s? Thanks in advance

**Comment by MatthewBCooke** [comment]
Hi @filos93,

In terms of application to a barnes maze, some parameters in the code would need to be slightly modified or the appropriate output ignored. Also some parameters such as chaining and thigmotaxis would no longer be relevant.
